# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EkuidistanDialog
                                 A QGIS plugin
 Penentuan Garis Ekuidistan dengan Pembobotan Pulau Kecil Untuk Delimitasi Batas Maritim Internasional
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-10-19
        git sha              : $Format:%H$
        copyright            : (C) 2024 by PRGG_8_2024
        email                : krishnaduta12345@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtCore import pyqtSignal
from qgis.gui import QgsMapToolEmitPoint, QgsMessageBar, QgsVertexMarker
from qgis.core import *
from qgis.utils import reloadPlugin
from qgis.PyQt.QtWidgets import QDialog, QCheckBox, QVBoxLayout


# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'ekuidistan_dialog_base.ui'))


class EkuidistanDialog(QtWidgets.QDialog, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(EkuidistanDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        layout = QVBoxLayout(self)
        
        # Create checkbox
        # Set layout for the dialog
        self.setLayout(layout)
        self.setupUi(self)
        self.input_mode = ""

    def on_btnclose_pressed(self):
        self.close()
    


